version: '3.7'
services:
  minio:
    restart: always
    image: 'bitnami/minio:latest'
    container_name: minio1
    hostname: minio1
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=账号
      - MINIO_ROOT_PASSWORD=密码
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio1,minio2,minio3,minio4
      - MINIO_SKIP_CLIENT=yes
    extra_hosts:
      - "minio1:192.168.1.1"  # 节点1和对应的IP地址
      - "minio2:192.168.1.2"  # 节点2和对应的IP地址
      - "minio3:192.168.1.3"  # 节点3和对应的IP地址
      - "minio4:192.168.1.4"  # 节点4和对应的IP地址
    volumes:
      - ./data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3  
